export const sampleImgList = [
  {
    id: "000001",
    url: "/src/assets/samples/a.png",
    prevUrl: "/src/assets/samples/a.png",
    fileName: "test01",
    description: "test",
    likeCount: 3,
  },
  {
    id: "000002",
    url: "/src/assets/samples/b.png",
    prevUrl: "/src/assets/samples/b.png",
    fileName: "test02",
    description: "test",
    likeCount: 5,
  },
  {
    id: "000003",
    url: "/src/assets/samples/c.png",
    prevUrl: "/src/assets/samples/c.png",
    fileName: "test03",
    description: "test",
    likeCount: 3,
  },
  {
    id: "000004",
    url: "/src/assets/samples/d.png",
    prevUrl: "/src/assets/samples/d.png",
    fileName: "test04",
    description: "test",
    likeCount: 3,
  },
  {
    id: "000005",
    url: "/src/assets/samples/e.png",
    prevUrl: "/src/assets/samples/e.png",
    fileName: "test05",
    description: "test",
    likeCount: 3,
  },
  {
    id: "000006",
    url: "/src/assets/samples/f.png",
    prevUrl: "/src/assets/samples/f.png",
    fileName: "test06",
    description: "test",
    likeCount: 10,
  },
  {
    id: "000007",
    url: "/src/assets/samples/g.png",
    prevUrl: "/src/assets/samples/g.png",
    fileName: "test07",
    description: "test",
    likeCount: 10,
  },
  {
    id: "000008",
    url: "/src/assets/samples/h.png",
    prevUrl: "/src/assets/samples/h.png",
    fileName: "test08",
    description: "test",
    likeCount: 1,
  },
  {
    id: "000009",
    url: "/src/assets/samples/i.png",
    prevUrl: "/src/assets/samples/i.png",
    fileName: "test09",
    description: "test",
    likeCount: 16,
  },
  {
    id: "000010",
    url: "/src/assets/samples/j.png",
    prevUrl: "/src/assets/samples/j.png",
    fileName: "test10",
    description: "test",
    likeCount: 17,
  },
  {
    id: "000011",
    url: "/src/assets/samples/k.png",
    prevUrl: "/src/assets/samples/k.png",
    fileName: "test11",
    description: "test",
    likeCount: 12,
  },
  {
    id: "000012",
    url: "/src/assets/samples/l.png",
    prevUrl: "/src/assets/samples/l.png",
    fileName: "test12",
    description: "test",
    likeCount: 14,
  },
  {
    id: "000013",
    url: "/src/assets/samples/m.png",
    prevUrl: "/src/assets/samples/m.png",
    fileName: "test13",
    description: "test",
    likeCount: 9,
  },
  {
    id: "000014",
    url: "/src/assets/samples/n.png",
    prevUrl: "/src/assets/samples/n.png",
    fileName: "test14",
    description: "test",
    likeCount: 20,
  },
  {
    id: "000015",
    url: "/src/assets/samples/o.png",
    prevUrl: "/src/assets/samples/o.png",
    fileName: "test15",
    description: "test",
    likeCount: 16,
  },
  {
    id: "000016",
    url: "/src/assets/samples/p.png",
    prevUrl: "/src/assets/samples/p.png",
    fileName: "test16",
    description: "test",
    likeCount: 4,
  },
  {
    id: "000017",
    url: "/src/assets/samples/q.png",
    prevUrl: "/src/assets/samples/q.png",
    fileName: "test17",
    description: "test",
    likeCount: 12,
  },
  {
    id: "000018",
    url: "/src/assets/samples/r.png",
    prevUrl: "/src/assets/samples/r.png",
    fileName: "test18",
    description: "test",
    likeCount: 4,
  },
];

export const description =
  "Welcome to my photography space! I'm passionate about capturing moments that tell a story and bring out the beauty in everyday life. Photography has always been a hobby of mine, and I love sharing the photos I take during my free time. On this site, you'll find a collection of my work, and I'd love for you to explore, comment, and engage with the images that resonate with you. Thanks for visiting, and I hope my photos inspire you as much as they've inspired me.";
